use customer_behavior;

-- What is the total revenue generated by male vs. female customers?
select gender , sum(purchase_amount_) as "total revenue"
from customer_behavior
group by gender ;

-- Which customers used a discount but still spent more than the average purchase amount? 
select customer_id , purchase_amount_
from customer_behavior
where discount_applied= 'Yes' and purchase_amount_ > (select avg (purchase_amount_) from customer_behavior);

-- Which are the top 5 products with the highest average review rating?
select Top 5 item_purchased , round( AVG (review_rating),3) as "avrage rating"
from customer_behavior
group by item_purchased
order by avg(review_rating) desc;

-- Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type , avg(purchase_amount_) as "avrage"
from customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Compare average spend and total revenue between subscribers and non-subscribers.
select count (customer_id) as total_customers ,subscription_status , avg (purchase_amount_) as avg_spend ,
sum (purchase_amount_) as total_revenue
from customer_behavior
group by subscription_status
order by avg(purchase_amount_) desc , sum(purchase_amount_) desc ;

-- Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased , 100.0* (sum( case when discount_applied = 'Yes' then 1.0 else 0 end ) / count(*)) as "discount_percentage"
from customer_behavior
group by item_purchased
order by discount_percentage desc;

-- Segmenting customers into New, Returning, and Loyal based on their total number of previous purchases,
-- and show the count of each segment. 
with customer_type as
(
select customer_id, previous_purchases ,
case 
when  previous_purchases = 1 then 'new'
when previous_purchases between 2 and 10 then 'Returning'
else  'Loyal'
end as customer_segment
from customer_behavior
)
select  customer_segment , count(*) as "count of customers"
from customer_type 
group by customer_segment
order by "count of customers" desc;

-- customers who are repeat buyers more than 5 previous purchases
select subscription_status , count (customer_id) as "number of buying"
from customer_behavior
where previous_purchases > 5 
group by subscription_status;

-- What is the revenue contribution of each age group? 
select age_groub , sum(purchase_amount_) as "total revenue"
from customer_behavior
group by age_groub
order by "total revenue" desc;



